# -*- coding: utf-8 -*-
"""检查并修复 app_logs 表结构问题"""
import os
import sys

# 添加项目根目录到 Python 路径
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, project_root)

# 手动加载环境变量
env_path = os.path.join(project_root, ".env")
if os.path.exists(env_path):
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                os.environ[key.strip()] = value.strip()

from supabase import create_client

print("=" * 60)
print("检查 Supabase 连接和 app_logs 表")
print("=" * 60)

# 检查环境变量
print("\n1. 检查环境变量:")
url = os.getenv("SUPABASE_URL")
key = os.getenv("SUPABASE_KEY")
print(f"   SUPABASE_URL: {url}")
print(f"   SUPABASE_KEY: {'***' if key else 'None'}")

if not url or not key:
    print("\n✗ 缺少 SUPABASE_URL 或 SUPABASE_KEY")
    sys.exit(1)

# 测试连接
print("\n2. 测试 Supabase 连接:")
try:
    supabase = create_client(url, key)
    print("   ✓ Supabase 客户端创建成功")
except Exception as e:
    print(f"   ✗ Supabase 客户端创建失败: {e}")
    sys.exit(1)

# 测试 app_logs 表
print("\n3. 测试 app_logs 表:")
try:
    # 尝试查询表
    result = supabase.table("app_logs").select("count").execute()
    print(f"   ✓ app_logs 表存在，当前记录数: {len(result.data) if result.data else 0}")
except Exception as e:
    print(f"   ✗ app_logs 表查询失败: {e}")
    print("\n   请确保 app_logs 表存在，并且结构正确。")
    print("\n   app_logs 表的 SQL 结构应该是:")
    print("   CREATE TABLE public.app_logs (")
    print("       id BIGINT GENERATED BY DEFAULT AS IDENTITY,")
    print("       level TEXT NOT NULL,")
    print("       message TEXT NOT NULL,")
    print("       context JSONB,")
    print("       user_id TEXT,")
    print("       created_at TIMESTAMPTZ DEFAULT NOW(),")
    print("       CONSTRAINT app_logs_pkey PRIMARY KEY (id)")
    print("   );")
    sys.exit(1)

# 测试写入
print("\n4. 测试写入 app_logs 表:")
try:
    test_payload = {
        "level": "info",
        "message": "测试日志写入",
        "context": '{"test": "value"}',
        "user_id": "test_user"
    }
    result = supabase.table("app_logs").insert(test_payload).execute()
    print("   ✓ 测试日志写入成功")
    print(f"   写入的记录: {result.data}")
except Exception as e:
    print(f"   ✗ 测试日志写入失败: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)

print("\n" + "=" * 60)
print("所有检查通过！")
print("=" * 60)
